version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your-key

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend